export const clothingGears = [
  "Enchanted Robe",
  "Fresh Fish Gloves",
  "Marinated Top",
  "Pearlescent Hoodie",
  "Power Armor",
  "Power Armor Mk I",
  "Samurai Jacket",
  "School Cardigan",
  "School Uniform",
  "Squinja Suit",
  "Steel Platemail",
  "Annaki Blue Cuff",
  "Annaki Drive Tee ",
  "Annaki Evolution Tee",
  "Annaki Flannel Hoodie",
  "Annaki Polpo-Pic Tee",
  "Annaki Red Cuff",
  "Annaki Yellow Cuff",
  "Crimson Parashooter",
  "Hula Punk Shirt",
  "Prune Parashooter",
  "Red Hula Punk with Tie",
  "Rockin' Leather Jacket",
  "Armor Jacket Replica",
  "Black Cuttlegear LS",
  "Fresh Octo Tee",
  "Hero Hoodie Replica",
  "Hero Jacket Replica",
  "Neo Octoling Armor",
  "Null Armor Replica",
  "Octarian Retro",
  "Octo Layered LS",
  "Octo Tee",
  "Old-Timey Clothes",
  "Red Cuttlegear LS",
  "Sennyu Suit",
  "Black Velour Octoking Tee ",
  "Grape Hoodie",
  "Green Velour Octoking Tee",
  "King Jersey",
  "Milky Eminence Jacket",
  "N-Pacer Sweat",
  "Navy Eminence Jacket",
  "Navy King Tank",
  "Octoking HK Jersey",
  "Slash King Tank",
  "White King Tank",
  "Baseball Jersey",
  "Black 8-Bit FishFry",
  "Blue 16-Bit FishFry",
  "Camo Zip Hoodie",
  "Carnivore Tee",
  "Dark Urban Vest",
  "Firefin Navy Sweat",
  "Fugu Tee",
  "Gray 8-Bit FishFry",
  "Green Zip Hoodie",
  "Herbivore Tee",
  "Khaki 16-Bit FishFry",
  "White 8-Bit FishFry",
  "Yellow Urban Vest",
  "ω-3 Tee",
  "Aloha Shirt",
  "Blue Sailor Suit",
  "Brown FA-11 Bomber",
  "Custom Painted F-3 ",
  "FA-01 Jacket",
  "FA-01 Reversed",
  "Forge Inkling Parka",
  "Forge Octarian Jacket",
  "Gray FA-11 Bomber",
  "Green Tee",
  "Moist Ghillie Suit",
  "White Leather F-3",
  "White Sailor Suit",
  "Anchor Life Vest",
  "Crustwear XXL",
  "Dev Uniform",
  "Garden Gear",
  "Juice Parka",
  "North-Country Parka",
  "Octoleet Armor",
  "Office Attire",
  "Online Jersey",
  "Record Shop Look EP",
  "Squiddor Polo",
  "SRL Coat",
  "Berry Ski Jacket",
  "Blue Peaks Tee",
  "Chili-Pepper Ski Jacket",
  "Chilly Mountain Coat",
  "Eggplant Mountain Coat",
  "Fishing Vest",
  "Forest Vest",
  "Green Striped LS",
  "Ivory Peaks Tee",
  "Matcha Down Jacket",
  "Mountain Vest",
  "Olive Ski Jacket",
  "Striped Peaks LS",
  "Chili Octo Aloha",
  "Krak-On 528",
  "Missus Shrug Tee",
  "Mister Shrug Tee",
  "Octobowler Shirt",
  "Rainy-Day Tee",
  "Rodeo Shirt",
  "Squid-Pattern Waistcoat",
  "Squidstar Waistcoat",
  "Sunny-Day Tee",
  "Black Baseball LS",
  "Black Inky Rider",
  "Black Urchin Rock Tee",
  "Chirpy Chips Band Tee",
  "Hightide Era Band Tee",
  "Lumberjack Shirt",
  "Rockenberg Black",
  "Rockenberg White",
  "Round-Collar Shirt",
  "Squid Squad Band Tee",
  "Vintage Check Shirt",
  "Wet Floor Band Tee",
  "White Baseball LS",
  "White Inky Rider",
  "White Urchin Rock Tee",
  "Black Hoodie",
  "Dots-On-Dots Shirt",
  "Firewave Tee",
  "Grape Tee",
  "Gray Hoodie",
  "Hothouse Hoodie",
  "Icewave Tee",
  "Mint Tee",
  "Pearl Tee",
  "Reggae Tee",
  "Squid-Stitch Tee",
  "Baby-Jelly Shirt",
  "Baby-Jelly Shirt & Tie",
  "Gray College Sweat",
  "Green Cardigan",
  "Lime Easy-Stripe Shirt",
  "Linen Shirt",
  "Navy College Sweat",
  "Navy Striped LS",
  "Orange Cardigan",
  "Pink Easy-Stripe Shirt",
  "Pink Hoodie",
  "Pirate-Stripe Tee",
  "Sage Polo",
  "Sailor-Stripe Tee",
  "Shirt & Tie",
  "Shirt with Blue Hoodie",
  "Shrimp-Pink Polo",
  "Striped Shirt",
  "Varsity Baseball LS",
  "Whale-Knit Sweater",
  "White Shirt",
  "White Striped LS",
  "Anchor Sweat",
  "Basic Tee",
  "Black Anchor Tee",
  "Black Layered LS",
  "Black Tee",
  "Black V-Neck Tee",
  "Camo Layered LS",
  "Friend Tee",
  "Green V-Neck Limited Tee",
  "Layered Anchor LS",
  "League Tee",
  "Mecha Body - AKM",
  "Octo Support Hoodie",
  "Red V-Neck Limited Tee",
  "Retro Sweat",
  "Splatfest Tee",
  "Squid Yellow Layered LS",
  "Squidmark LS",
  "Squidmark Sweat",
  "SWC Logo Tee",
  "White Anchor Tee",
  "White Layered LS",
  "White LS",
  "White Tee",
  "White V-Neck Tee",
  "Yellow Layered LS",
  "Choco Layered LS",
  "FC Albacore",
  "Gray Vector Tee",
  "Layered Vector LS",
  "Purple Camo LS",
  "Red Vector Tee",
  "Slipstream United",
  "Striped Rugby",
  "Takoroka Crazy Baseball LS",
  "Takoroka Galactic Tie Dye",
  "Takoroka Jersey",
  "Takoroka Nylon Vintage",
  "Takoroka Rainbow Tie Dye",
  "Takoroka Windcrusher",
  "Tricolor Rugby",
  "Black Squideye",
  "Blue Tentatek Tee",
  "Cycle King Jersey",
  "Lob-Stars Jersey",
  "Part-Time Pirate",
  "Red Tentatek Tee",
  "Silver Tentatek Vest",
  "Sky-Blue Squideye",
  "Tentatek Slogan Tee",
  "Dark Bomber Jacket",
  "Front Zip Vest",
  "Half-Sleeve Sweater",
  "Ink-Wash Shirt",
  "Inkfall Shirt",
  "Kensa Coat",
  "Kung-Fu Zip-Up",
  "Light Bomber Jacket",
  "Negative Longcuff Sweater",
  "Panda Kung-Fu Zip-Up",
  "Positive Longcuff Sweater",
  "Pullover Coat",
  "Short Knit Layers",
  "Toni K. Baseball Jersey",
  "Birded Corduroy Jacket",
  "Black LS",
  "Black Polo",
  "Deep-Octo Satin Jacket",
  "Gray Mixed Shirt",
  "Green-Check Shirt",
  "Logo Aloha Shirt",
  "Olive Zekko Parka",
  "Red-Check Shirt",
  "Reel Sweat",
  "Squid Satin Jacket",
  "Tumeric Zekko Coat",
  "Varsity Jacket",
  "Zapfish Satin Jacket",
  "Zekko Baseball LS",
  "Zekko Hoodie",
  "Zekko Jade Coat",
  "Zekko Long Carrot Tee",
  "Zekko Long Radish Tee",
  "Zekko Redleaf Coat",
  "B-ball Jersey (Away)",
  "B-ball Jersey (Home)",
  "Cycling Shirt",
  "Dakro Golden Tee",
  "Dakro Nana Tee",
  "Inkopolis Squaps Jersey",
  "Navy Deca Logo Tee",
  "Retro Gamer Jersey",
  "School Jersey",
  "Urchins Jersey",
  "White Deca Logo Tee",
  "Zink Layered LS",
  "Zink LS",
] as const;
