export const headGears = [
  "Enchanted Hat",
  "Fresh Fish Head",
  "Marinated Headphones",
  "Pearlescent Crown",
  "Power Mask",
  "Power Mask Mk I",
  "Samurai Helmet",
  "Squid Clip-Ons",
  "Squid Hairclip",
  "Squinja Mask",
  "Steel Helm",
  "Annaki Beret",
  "Annaki Beret & Glasses",
  "Annaki Mask",
  "Armor Helmet Replica",
  "Conductor Cap",
  "Golden Toothpick",
  "Hero Headphones Replica",
  "Hero Headset Replica",
  "Null Visor Replica",
  "Octoling Shades",
  "Old-Timey Hat",
  "Studio Octophones",
  "Eminence Cuff",
  "King Facemask",
  "King Flip Mesh",
  "Octoking Facemask",
  "Black FishFry Bandana",
  "Blowfish Bell Hat",
  "Blowfish Newsie",
  "Camo Mesh",
  "Firefin Facemask",
  "FishFry Biscuit Bandana",
  "FishFry Visor",
  "Fugu Bell Hat",
  "Jet Cap",
  "Jungle Hat",
  "Knitted Hat",
  "Octoglasses",
  "Deca Tackle Visor Helmet",
  "Designer Headphones",
  "Digi-Camo Forge Mask",
  "Forge Mask",
  "Gas Mask",
  "Hockey Helmet",
  "Moist Ghillie Helmet",
  "Motocross Nose Guard",
  "Noise Cancelers",
  "Octo Tackle Helmet Deco",
  "Paintball Mask",
  "Pilot Goggles",
  "Safari Hat",
  "Sennyu Goggles",
  "Sennyu Headphones",
  "Skull Bandana",
  "Snorkel Mask",
  "Special Forces Beret",
  "Splash Goggles",
  "Squidfin Hook Cans",
  "Squidlife Headphones",
  "Stealth Goggles",
  "Studio Headphones",
  "Treasure Hunter",
  "Beekeeper Hat",
  "Cap of Legend",
  "Dust Blocker 2000",
  "Headlamp Helmet",
  "Oceanic Hard Hat",
  "Octoleet Goggles",
  "Sailor Cap",
  "Welding Mask",
  "Worker's Cap",
  "Worker's Head Towel",
  "Bamboo Hat",
  "Camping Hat",
  "Lightweight Cap",
  "Mountie Hat",
  "Seashell Bamboo Hat",
  "Short Beanie",
  "Tulip Parasol",
  "Yamagiri Beanie",
  "Full Moon Glasses",
  "Hickory Work Cap",
  "Long-Billed Cap",
  "Paisley Bandana",
  "Two-Stripe Mesh",
  "Woolly Urchins Classic",
  "18K Aviators",
  "SV925 Circle Shades",
  "Bike Helmet",
  "Classic Straw Boater",
  "Do-Rag, Cap, & Glasses",
  "Hothouse Hat",
  "Jellyvader Cap",
  "Patched Hat",
  "Skate Helmet",
  "Sneaky Beanie",
  "Sporty Bobble Hat",
  "Squid Nordic",
  "Squid-Stitch Cap",
  "Squidvader Cap",
  "Straw Boater",
  "Streetstyle Cap",
  "Urchins Cap",
  "Visor Skate Helmet",
  "Bobble Hat",
  "Half-Rim Glasses",
  "House-Tag Denim Cap",
  "Pilot Hat",
  "Retro Specs",
  "Sennyu Bon Bon Beanie",
  "Sennyu Specs",
  "Striped Beanie",
  "Anglerfish Mask",
  "Bucket Hat",
  "Eel-Cake Hat",
  "Festive Party Cone",
  "Hockey Mask",
  "Koshien Bandana",
  "Kyonshi Hat",
  "Li'l Devil Horns",
  "Mecha Head - HTR",
  "New Year's Glasses DX",
  "Painter's Mask",
  "Squid Facemask",
  "Twisty Headband",
  "White Headband",
  "Jetflame Crest",
  "Fierce Fishskull",
  "Hivemind Antenna",
  "Eye of Justice",
  "Takoroka Mesh",
  "Takoroka Visor",
  "Cycle King Cap",
  "Fake Contacts",
  "Green Novelty Visor",
  "Orange Novelty Visor",
  "Pink Novelty Visor",
  "Purple Novelty Visor",
  "Soccer Headband",
  "Sun Visor",
  "Tennis Headband",
  "Face Visor",
  "Ink-Guard Goggles",
  "Toni Kensa Goggles",
  "Backwards Cap",
  "Black Arrowbands",
  "Double Egg Shades",
  "Five-Panel Cap",
  "Jogging Headband",
  "Matte Bike Helmet",
  "MTB Helmet",
  "Tinted Shades",
  "White Arrowbands",
  "Zekko Cap",
  "Zekko Mesh",
  "B-ball Headband",
  "Cycling Cap",
  "Golf Visor",
  "Squash Headband",
  "Swim Goggles",
] as const;
