export const shoesGears = [
  "Enchanted Boots",
  "Fresh Fish Feet",
  "Fringed Loafers",
  "Marinated Slip-Ons",
  "Pearlescent Kicks",
  "Power Boots",
  "Power Boots Mk I",
  "Samurai Shoes",
  "School Shoes",
  "Squinja Boots",
  "Steel Greaves",
  "Annaki Arachno Boots",
  "Annaki Habaneros",
  "Annaki Tigers",
  "Armor Boot Replicas",
  "Hero Runner Replicas",
  "Hero Snowboots Replicas",
  "Neo Octoling Boots",
  "Null Boots Replica",
  "Old-Timey Shoes",
  "Black & Blue Squidkid V",
  "Blue & Black Squidkid IV",
  "Honey & Orange Squidkid V",
  "Milky Enperrials",
  "N-Pacer Ag",
  "N-Pacer Au",
  "N-Pacer CaO",
  "Navy Enperrials",
  "Online Squidkid V",
  "Pearlescent Squidkid IV",
  "Red & Black Squidkid IV",
  "Red & White Squidkid V",
  "Rina Squidkid IV",
  "Sun & Shade Squidkid IV",
  "Red FishFry Sandals",
  "Yellow FishFry Sandals",
  "Moist Ghillie Boots",
  "Angry Rain Boots",
  "Flipper Floppers",
  "Friendship Bracelet",
  "Non-slip Senseis",
  "Octoleet Boots",
  "Wooden Sandals",
  "Acerola Rain Boots",
  "Birch Climbing Shoes",
  "Bubble Rain Boots",
  "Custom Trail Boots",
  "Green Rain Boots",
  "Luminous Delta Straps",
  "Musselforge Flip-Flops",
  "Neon Delta Straps",
  "Pro Trail Boots",
  "Snow Delta Straps",
  "Sunny Climbing Shoes",
  "Trail Boots",
  "Banana Basics",
  "Blue Slip-Ons",
  "Blueberry Casuals",
  "Choco Clogs",
  "Clownfish Basics",
  "Cream Basics",
  "Cream Hi-Tops",
  "Hunter Hi-Tops",
  "Midnight Slip-Ons",
  "Oyster Clogs",
  "Plum Casuals",
  "Polka-dot Slip-Ons",
  "Red Hi-Tops",
  "Red Slip-Ons",
  "Squid-Stitch Slip-Ons",
  "Truffle Canvas Hi-Tops",
  "Blue Moto Boots",
  "Cherry Kicks",
  "Deepsea Leather Boots",
  "Gray Yellow-Soled Wingtips",
  "Inky Kid Clams",
  "Kid Clams",
  "Moto Boots",
  "Navy Red-Soled Wingtips",
  "New-Leaf Leather Boots",
  "Pearl Punk Crowns",
  "Punk Blacks",
  "Punk Cherries",
  "Punk Whites",
  "Punk Yellows",
  "Red Work Boots",
  "Roasted Brogues",
  "Sennyu Inksoles",
  "Smoky Wingtips",
  "Squink Wingtips",
  "Tan Work Boots",
  "Turquoise Kicks",
  "White Kicks",
  "Green Laceups",
  "Hunting Boots",
  "Mawcasins",
  "Piranha Moccasins",
  "Shark Moccasins",
  "Strapping Reds",
  "Strapping Whites",
  "Tea-Green Hunting Boots",
  "Mecha Legs - LBS",
  "Athletic Arrows",
  "Blue Power Stripes",
  "Crazy Arrows",
  "LE Soccer Shoes",
  "New-Day Arrows",
  "Orange Arrows",
  "Orca Hi-Tops",
  "Orca Passion Hi-Tops",
  "Orca Woven Hi-Tops",
  "Red Power Stripes",
  "Soccer Shoes",
  "Sunset Orca Hi-Tops",
  "Trooper Power Stripes",
  "White Arrows",
  "Amber Sea Slug Hi-Tops",
  "Black Norimaki 750s",
  "Black Trainers",
  "Blue Iromaki 750s",
  "Blue Sea Slugs",
  "Canary Trainers",
  "Cyan Trainers",
  "Gray Sea-Slug Hi-Tops",
  "Green Iromaki 750s",
  "Icy Down Boots",
  "Neon Sea Slugs",
  "Orange Iromaki 750s",
  "Pink Trainers",
  "Purple Iromaki 750s",
  "Purple Sea Slugs",
  "Red Iromaki 750s",
  "Red Sea Slugs",
  "Red-Mesh Sneakers",
  "Sea Slug Volt 95s",
  "Sesame Salt 270s",
  "Snowy Down Boots",
  "Violet Trainers",
  "White Norimaki 750s",
  "Yellow Iromaki 750s",
  "Yellow-Mesh Sneakers",
  "Arrow Pull-Ons",
  "Toni Kensa Black Hi-Tops",
  "Toni Kensa Soccer Shoes",
  "Black Flip-Flops",
  "Blue Lo-Tops",
  "LE Lo-Tops",
  "Marination Lace-Ups",
  "Orange Lo-Tops",
  "Pearl-Scout Lace-Ups",
  "Suede Gray Lace-Ups",
  "Suede Marine Lace-Ups",
  "Suede Nation Lace-Ups",
  "Black Dakroniks",
  "Black Seahorses",
  "Blue Laceless Dakroniks",
  "Chocolate Dakroniks",
  "Gold Hi-Horses",
  "Mint Dakroniks",
  "Purple Hi-Horses",
  "Red Hi-Horses",
  "White Laceless Dakroniks",
  "White Seahorses",
  "Yellow Seahorses",
  "Zombie Hi-Horses",
] as const;
