import { Weapon } from "../types";

export const weaponToLinkCode: Record<Weapon, string> = {
  "Clash Blaster Neo": "clash-blaster-neo",
  "Heavy Splatling Deco": "heavy-splatling-deco",
  "Hero Slosher Replica": "hero-slosher-replica",
  Bloblobber: "bloblobber",
  "Kensa Splat Dualies": "kensa-splat-dualies",
  "Heavy Splatling Remix": "heavy-splatling-remix",
  "Goo Tuber": "goo-tuber",
  "Kensa Luna Blaster": "kensa-luna-blaster",
  Inkbrush: "inkbrush",
  "Custom Splattershot Jr.": "custom-splattershot-jr",
  Explosher: "explosher",
  "Rapid Blaster Deco": "rapid-blaster-deco",
  "Grim Range Blaster": "grim-range-blaster",
  "Hero Blaster Replica": "hero-blaster-replica",
  "Clash Blaster": "clash-blaster",
  "Luna Blaster Neo": "luna-blaster-neo",
  "Aerospray RG": "aerospray-rg",
  Blaster: "blaster",
  ".52 Gal": "52-gal",
  "Tenta Camo Brella": "tenta-camo-brella",
  "Dapple Dualies": "dapple-dualies",
  ".96 Gal Deco": "96-gal-deco",
  "Kensa Splat Roller": "kensa-splat-roller",
  "Hero Splatling Replica": "hero-splatling-replica",
  "Krak-On Splat Roller": "krak-on-splat-roller",
  "Tenta Brella": "tenta-brella",
  "Kensa Sloshing Machine": "kensa-sloshing-machine",
  "E-liter 4K Scope": "e-liter-4k-scope",
  "Kensa Undercover Brella": "kensa-undercover-brella",
  ".96 Gal": "96-gal",
  "Kensa Rapid Blaster": "kensa-rapid-blaster",
  "Custom Blaster": "custom-blaster",
  "Flingza Roller": "flingza-roller",
  "Custom Goo Tuber": "custom-goo-tuber",
  "Custom E-liter 4K": "custom-e-liter-4k",
  "Dynamo Roller": "dynamo-roller",
  "Tentatek Splattershot": "tentatek-splattershot",
  "Kensa .52 Gal": "kensa-52-gal",
  "Splattershot Pro": "splattershot-pro",
  "Rapid Blaster Pro Deco": "rapid-blaster-pro-deco",
  "Custom Hydra Splatling": "custom-hydra-splatling",
  "N-ZAP '83": "n-zap-83",
  "L-3 Nozzlenose D": "l-3-nozzlenose-d",
  "Kensa Octobrush": "kensa-octobrush",
  "Sploosh-o-matic 7": "sploosh-o-matic-7",
  "Foil Squeezer": "foil-squeezer",
  "Custom Explosher": "custom-explosher",
  "Luna Blaster": "luna-blaster",
  "Kensa Mini Splatling": "kensa-mini-splatling",
  "L-3 Nozzlenose": "l-3-nozzlenose",
  "Nautilus 47": "nautilus-47",
  "Slosher Deco": "slosher-deco",
  "Forge Splattershot Pro": "forge-splattershot-pro",
  "Ballpoint Splatling": "ballpoint-splatling",
  "Cherry H-3 Nozzlenose": "cherry-h-3-nozzlenose",
  "Dapple Dualies Nouveau": "dapple-dualies-nouveau",
  "Dualie Squelchers": "dualie-squelchers",
  "Undercover Sorella Brella": "undercover-sorella-brella",
  "Classic Squiffer": "classic-squiffer",
  "Kensa Charger": "kensa-charger",
  "Bamboozler 14 Mk II": "bamboozler-14-mk-ii",
  "Aerospray MG": "aerospray-mg",
  Slosher: "slosher",
  "Carbon Roller": "carbon-roller",
  "Soda Slosher": "soda-slosher",
  "Hero Charger Replica": "hero-charger-replica",
  "Bamboozler 14 Mk III": "bamboozler-14-mk-iii",
  "Bloblobber Deco": "bloblobber-deco",
  Squeezer: "squeezer",
  "Hero Roller Replica": "hero-roller-replica",
  "Hero Dualie Replicas": "hero-dualie-replicas",
  "Custom E-liter 4K Scope": "custom-e-liter-4k-scope",
  "H-3 Nozzlenose": "h-3-nozzlenose",
  "Rapid Blaster": "rapid-blaster",
  "Splash-o-matic": "splash-o-matic",
  "Fresh Squiffer": "fresh-squiffer",
  "Custom Dualie Squelchers": "custom-dualie-squelchers",
  "Kensa L-3 Nozzlenose": "kensa-l-3-nozzlenose",
  "Heavy Splatling": "heavy-splatling",
  "Range Blaster": "range-blaster",
  "Aerospray PG": "aerospray-pg",
  "Undercover Brella": "undercover-brella",
  "Kensa Splatterscope": "kensa-splatterscope",
  "Kensa Splattershot Jr.": "kensa-splattershot-jr",
  "Enperry Splat Dualies": "enperry-splat-dualies",
  "Foil Flingza Roller": "foil-flingza-roller",
  "N-ZAP '89": "n-zap-89",
  "Tri-Slosher Nouveau": "tri-slosher-nouveau",
  "Octo Shot Replica": "octo-shot-replica",
  "Sploosh-o-matic": "sploosh-o-matic",
  "Sorella Brella": "sorella-brella",
  "Kensa Glooga Dualies": "kensa-glooga-dualies",
  "N-ZAP '85": "n-zap-85",
  "Hero Shot Replica": "hero-shot-replica",
  "Sloshing Machine": "sloshing-machine",
  "Zink Mini Splatling": "zink-mini-splatling",
  "Jet Squelcher": "jet-squelcher",
  "Splat Roller": "splat-roller",
  "Tri-Slosher": "tri-slosher",
  "Clear Dapple Dualies": "clear-dapple-dualies",
  "Custom Range Blaster": "custom-range-blaster",
  "E-liter 4K": "e-liter-4k",
  Octobrush: "octobrush",
  "Tenta Sorella Brella": "tenta-sorella-brella",
  "Hydra Splatling": "hydra-splatling",
  "Mini Splatling": "mini-splatling",
  "Firefin Splatterscope": "firefin-splatterscope",
  "Nautilus 79": "nautilus-79",
  ".52 Gal Deco": "52-gal-deco",
  "Neo Splash-o-matic": "neo-splash-o-matic",
  "Inkbrush Nouveau": "inkbrush-nouveau",
  "Kensa Splattershot": "kensa-splattershot",
  "Octobrush Nouveau": "octobrush-nouveau",
  "Splat Brella": "splat-brella",
  "Bamboozler 14 Mk I": "bamboozler-14-mk-i",
  "New Squiffer": "new-squiffer",
  "Splat Charger": "splat-charger",
  "Splat Dualies": "splat-dualies",
  "Firefin Splat Charger": "firefin-splat-charger",
  "Permanent Inkbrush": "permanent-inkbrush",
  "Herobrush Replica": "herobrush-replica",
  "Hero Brella Replica": "hero-brella-replica",
  Splatterscope: "splatterscope",
  "Gold Dynamo Roller": "gold-dynamo-roller",
  "Glooga Dualies": "glooga-dualies",
  "Custom Jet Squelcher": "custom-jet-squelcher",
  "Neo Sploosh-o-matic": "neo-sploosh-o-matic",
  "Kensa Dynamo Roller": "kensa-dynamo-roller",
  "Light Tetra Dualies": "light-tetra-dualies",
  "Splattershot Jr.": "splattershot-jr",
  "Dark Tetra Dualies": "dark-tetra-dualies",
  "Carbon Roller Deco": "carbon-roller-deco",
  "Kensa Splattershot Pro": "kensa-splattershot-pro",
  "Rapid Blaster Pro": "rapid-blaster-pro",
  "H-3 Nozzlenose D": "h-3-nozzlenose-d",
  "Glooga Dualies Deco": "glooga-dualies-deco",
  "Ballpoint Splatling Nouveau": "ballpoint-splatling-nouveau",
  Splattershot: "splattershot",
  "Sloshing Machine Neo": "sloshing-machine-neo",
} as const;
